import Head from "next/head";
import { LandingPage } from "@repo/shared/dist/server";
import { Demo } from "@repo/shared";

/** Landing page */
export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js Dark Mode | Next.js Pages Router Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage title="Next.js Pages Router Example">
        <Demo />
      </LandingPage>
    </>
  );
}
